r"""Build main.tex (IEEE journal format) from the thesis sources, word for word.

Only layout changes are made:
  * thesis chapters become IEEE sections (\section -> \subsection, etc.)
  * [H] floats become IEEE top floats; every float is set double-column
    (figure*/table*) because the thesis floats are sized for a full text width
  * figure paths point to this folder's figures/ directory
  * the first word of the Introduction gets the IEEE drop cap
The body text, tables, captions, equations and citations are copied unchanged.

Run from this folder:  python build_from_thesis.py
"""
import pathlib
import re
import shutil

HERE = pathlib.Path(__file__).resolve().parent
THESIS = HERE.parent

CHAPTERS = [
    ("Introduction", "chapters/chapter_1.tex"),
    ("Literature Review", "chapters/chapter_2.tex"),
    ("Requirements, Impacts and Constraints", "chapters/chapter_3.tex"),
    ("Proposed Methodology", "chapters/chapter_5.tex"),
    ("Result Analysis", "chapters/chapter_6.tex"),
    ("Conclusion", "chapters/chapter_9.tex"),
]


def read(rel):
    return (THESIS / rel).read_bytes().decode("utf-8").replace("\r\n", "\n")


def demote(text):
    """Shift heading levels down by one (chapter content sits under an IEEE \\section)."""
    text = re.sub(r"\\subsubsection(\*?)([\[{])", r"\\paragraph\1\2", text)
    text = re.sub(r"\\subsection(\*?)([\[{])", r"\\subsubsection\1\2", text)
    text = re.sub(r"\\section(\*?)([\[{])", r"\\subsection\1\2", text)
    return text


def ieee_floats(text):
    text = re.sub(r"\\begin\{figure\}\[H\]", r"\\begin{figure*}[!t]", text)
    text = text.replace("\\end{figure}", "\\end{figure*}")
    text = re.sub(r"\\begin\{table\}\[H\]", r"\\begin{table*}[!t]", text)
    text = text.replace("\\end{table}", "\\end{table*}")
    text = text.replace("images/generated/", "")
    text = text.replace("\\includegraphics[width=\\textwidth]", "\\includegraphics[width=0.8\\textwidth]")
    return text


# Equations wider than one IEEE column are broken across lines; the math is unchanged.
EQ_BREAKS = [
    (r"""\begin{equation}
    [r_{rgb}, r_{th}, r_{au}] = \sigma\!\left(W_2 \cdot \text{ReLU}(W_1 \cdot [\mathbf{q}_{rgb}\|\mathbf{q}_{th}\|\mathbf{q}_{au}\|\mathbf{s}] + b_1) + b_2\right)
\end{equation}""",
     r"""\begin{multline}
    [r_{rgb}, r_{th}, r_{au}] = \\ \sigma\!\left(W_2 \cdot \text{ReLU}(W_1 \cdot [\mathbf{q}_{rgb}\|\mathbf{q}_{th}\|\mathbf{q}_{au}\|\mathbf{s}] + b_1) + b_2\right)
\end{multline}"""),
    (r"""\begin{equation}
    \mathbf{P}_{\text{fire}} = \text{ReLU}\!\left(R - \tfrac{1}{2}(G + B)\right), \quad \mathbf{P}_{\text{smoke}} = 1 - \frac{\max(R,G,B) - \min(R,G,B)}{\max(R,G,B) + \epsilon}
\end{equation}""",
     r"""\begin{equation}
\begin{gathered}
    \mathbf{P}_{\text{fire}} = \text{ReLU}\!\left(R - \tfrac{1}{2}(G + B)\right), \\ \mathbf{P}_{\text{smoke}} = 1 - \frac{\max(R,G,B) - \min(R,G,B)}{\max(R,G,B) + \epsilon}
\end{gathered}
\end{equation}"""),
]


def break_equations(text):
    for old, new in EQ_BREAKS:
        text = text.replace(old, new)
    return text


def figures_used(text):
    return re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", text)


def main():
    abstract = read("core/abstract.tex")
    body_abs = abstract.split("\\section*{Abstract}", 1)[1]
    body_abs, kw = body_abs.split("\\textbf{Keywords:}", 1)
    body_abs = body_abs.replace("\\vspace{1cm}", "").strip()
    kw = kw.replace("\\pagebreak", "").strip()

    ethics = read("core/ethics_statement.tex").replace("\\pagebreak", "").strip()

    parts = []
    figs = []
    for title, rel in CHAPTERS:
        src = read(rel)
        figs += figures_used(src)
        src = break_equations(ieee_floats(demote(src)))
        if rel.endswith("chapter_1.tex"):
            src = src.replace("As the climate warms", "\\IEEEPARstart{A}{s} the climate warms", 1)
        parts.append(f"%{'=' * 69}\n\\section{{{title}}}\n%{'=' * 69}\n\n{src.strip()}\n")

    figdir = HERE / "figures"
    figdir.mkdir(exist_ok=True)
    for f in figs:
        name = f.replace("images/generated/", "")
        shutil.copy2(THESIS / "images/generated" / name, figdir / name)

    tex = TEMPLATE.replace("@@ABSTRACT@@", body_abs).replace("@@KEYWORDS@@", kw)
    tex = tex.replace("@@BODY@@", "\n\n".join(parts)).replace("@@ETHICS@@", ethics)
    (HERE / "main.tex").write_bytes(tex.encode("utf-8"))
    print(f"main.tex written; {len(figs)} figures copied")


TEMPLATE = r"""%% main.tex
%% UniAdapFuse: thesis text set in IEEE journal format.
%% Built on bare_jrnl.tex V1.4b (2015/08/26) by Michael Shell
%% (IEEEtran.cls, http://www.michaelshell.org/tex/ieeetran/);
%% the untouched template is kept alongside as bare_jrnl.tex.
%%
%% GENERATED by build_from_thesis.py from ../chapters/*.tex and ../core/*.tex.
%% The text is copied word for word; edit the thesis sources and re-run the
%% script rather than editing this file by hand.
%%
%% Build:  pdflatex main  ->  bibtex main  ->  pdflatex main  ->  pdflatex main

\documentclass[journal]{IEEEtran}

% *** CITATION PACKAGES ***
\usepackage{cite}

% *** GRAPHICS RELATED PACKAGES ***
\usepackage{graphicx}
\graphicspath{{figures/}}

% *** MATH PACKAGES ***
\usepackage{amsmath}
\usepackage{amssymb}
\interdisplaylinepenalty=2500

% *** TEXT / FONT ***
\usepackage[T1]{fontenc}
\usepackage{textcomp}

% *** ALIGNMENT / TABLE PACKAGES ***
\usepackage{array}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage[table]{xcolor}

% *** PDF, URL AND HYPERLINK PACKAGES ***
\usepackage{url}

% the thesis has many full-width floats
\extrafloats{100}
\renewcommand{\topfraction}{0.95}
\renewcommand{\dbltopfraction}{0.95}
\renewcommand{\textfraction}{0.05}
\renewcommand{\floatpagefraction}{0.8}
\renewcommand{\dblfloatpagefraction}{0.8}

% correct bad hyphenation here
\hyphenation{op-tical net-works semi-conduc-tor Uni-Adap-Fuse Adap-Fuse multi-modal}


\begin{document}

\title{UniAdapFuse: Reliability-Aware Multimodal Fusion\\ for UAV Disaster Perception}

\author{Humaira~Ayesha,
        Md~Saqline~Hossain,
        Badrunnaher~Pantho,
        Fatema~Siddika~Tanha,
        Md.~Irtiza~Hossain,
        and~Md.~Khalilur~Rhaman% <-this % stops a space
\thanks{H.~Ayesha, M.~S.~Hossain, B.~Pantho, and F.~S.~Tanha are with the Department of Computer Science and Engineering, BRAC University, Dhaka, Bangladesh (e-mail: humaira.ayesha@g.bracu.ac.bd; md.saqline.hossain@g.bracu.ac.bd; badrunnaher.pantho@g.bracu.ac.bd; fatema.siddika.tanha@g.bracu.ac.bd).}% <-this % stops a space
\thanks{M.~I.~Hossain and M.~K.~Rhaman are with the Department of Computer Science and Engineering, BRAC University, Dhaka, Bangladesh (e-mail: ext.irtiza.hossain@bracu.ac.bd; khalilur@bracu.ac.bd).}}

% The paper headers
\markboth{IEEE Journal, 2026}%
{Ayesha \MakeLowercase{\textit{et al.}}: UniAdapFuse: Reliability-Aware Multimodal Fusion for UAV Disaster Perception}

\maketitle

\begin{abstract}
@@ABSTRACT@@
\end{abstract}

\begin{IEEEkeywords}
@@KEYWORDS@@
\end{IEEEkeywords}

\IEEEpeerreviewmaketitle


@@BODY@@

%=====================================================================
@@ETHICS@@


% Can use something like this to put references on a page
% by themselves when using endfloat and the captionsoff option.
\ifCLASSOPTIONcaptionsoff
  \newpage
\fi

% references section
\bibliographystyle{IEEEtran}
\bibliography{references}

\end{document}
"""

if __name__ == "__main__":
    main()
